language: java

jdk:
  - openjdk16

script:
  - java --version
  - ./mvnw clean install
  - ./mvnw test

deploy:
  provider: heroku
  api_key:
    secure: 0c9db88e-02fc-4728-a4bc-d61ed3224357
  app: numberguessgame