language: java
jdk:
- openjdk16

services:
  - docker
  
env:
  global:
    - secure: Pf/reZKKKMZUiT+yXEFB3xrC5B5QWU/wWKsHgJ3thoAGKO1IyEjH/mTUARe+ooicppPXUgx6CTsgkOu2iczCdmCh1SV/2qzJ73t3giMJd/KnSR4IALeJqt+Dh+Hz9Q57PrmwWBAcggAlwYuaQggDr0WRppDIj0O6fgKV+2ypJR75v2vRzMsSl2M9raQmXhl2beCaxF7+TwkTROgobvkTaZUHUbnHiye4kYsBrC8jplLMS+ItcdxwYW1qSu1wEOcgJ/Ok49l5yL76yGTiKG9zrx0jJNUMOT3dnElumbO/BTHeTTK8OEYMonDkzA9tMq3p682YlCHS/sumZkelK1kz3AEy/Cg+KKeoR1NkvXIhMVuE2U8vcmY/BMr6z6hyuD1oqa89wzM13Gzwup4OQEbDl/n0DHWXh5K9Njmc2n4nfTuzfU4cnMxH7+F95RyDMUCuV0h9LBE1I12RJUJzIKCYRukXf/yg+4l4WmrHQwSjwxntGDn4vp08azr7oPXSGXOtY48nkmYa6n21FtI5tx347wE98qPX1Z3bTSQl4edOQv/FZeOvXeJQ9TTMtgdPjPaozSSQjKBjBGET3UpYrWo1fog5movexOmJJftv4roqlShopCSn+BzIQZmYzCqTuafvD3J6whBbrIxB+sMgnWbU8e4JGQUL6EC9nzTPUrWs58s=
    - secure: bjYcM6KOtI3tp52Xcj3t8OglKRcj7NsPzcN4M1YHAp2QOzUaMp85pYdCwRga55D2E7/PElcN+E8Y1ub3XZgQBj61y806L3BkPBPayv9g2FSl13RWkUhd30lLwsD2ltz7KMqAZfvGYQmdp+14JWDnohzVd4h/dpYehOFGvsLCi0RoWtDLmymM9Mj+s6ZD2VqrKMi8G+tClBlYa1q+qL0ILqLmD95G8ZgThOB/uG2hwaxFjXG+IkbZv1WUN3Ex15ipkMILV0nYjt6ERnkyv96z/uizrSXOX40w5PeI1Fm5z8UsQq3BFAsd1EU/3GQiN+DqydH1fGyTztWr9nATq1Xz+g4bCa6qsKzdW/OZm0XiUJYTJzVOvH16cl5dAYNvIBeUbrcbhohpYbzsloUEEg7+ljsxB9gP5HTRGvnPG4gta6IzXCrGu+yHO2nvJV9ozui99LTFxHFwIHDKhfR1ZKJTycynRQa3EwQcYxMt1HrT18ij9uyp8MAxnf9MA2BiXPZkDy3vF3RxGvTbQywOJVusNzYDX0gnB07Ykjof+tVCZMoJJrLdeNYtSPfbLSwd3768fnSNHOxphSq/ZSktUU1v7EXUYgYuw0bB9UaQSZkGtqZH3+6eH0DagMUTqV+ILIbLRA9z1/1yzAnt4Yj1V4RAWzM8ZiEqtokf1tspIY4tQGk=
    - secure: F0nMy1T3fC/PLNdO325pXYwDnz9hoFe4ohULN6RZuw/rwmWTzRsOYKXSK9kGsazzFqlqu6Icc3gwGeu9MnmoanX0FeU8h1bkWHgNRMTdhfFFFDQ4LdMcQDjYs6nuO9Vdp2j9uXRAT9GYXH08JXedcJmpdxYKAYboXYkpUH/oQO3Bu9UzMYSl3FlQSGqT83UP42xil+T75j1Pihz75Gi9soF7iGZvVokDWFGSR8hZDiR6HT5ZvQVsQT66grz+n8YJP0C5SZ8gDQWjUWsZZ39u1pJQYZrZmCm/zbTffYcEo4PV0zJ5UtFnIjyo3Yq57/e65V2DV1AClMwWwEp3ft30HYgDllQ/a+kD7+Ti4oJDH+1iIFkJ21ZrZ/h33y4QIP2rFGU9zlbqV2aIs0JQ0+q/u8Mm6E62ijh9Ds9+EedkChgPkx3UVCmL+ulrzAjtqbCEEYuFzLgIeu7qOKGMUFk0jOg+5CipPP9K9kO3Lisa4gjUOu4buSazRn8NdkuDZ19uL1f/mfTXC42hKyqmf2lgGP2JLqRF2soS9AHFk3mPnycX6g8fzz6nz3BZTcfWg7o7fn4t5pGZv6OVcjw28Fuw15y8GGXHoSLHg0KJuYdiEE3h+RHOKSae/2kU+/C2KsEK3oGjby+Zj6+riaJ7kDQIvOX5v7QaLNBmKWfqEBoHmUQ=
    - secure: Jq5feH+4pK2n/ig1aKDSGsVDWH17mpVLYhT/oV7dNO51aUn+OAgVmGYlfoP4P+GuhhxTuuCEGX7Yjh68Fq0apIuE8hk4pb6KUpVF9p2F0fQjmXwz7CyfV26JmnINcdpxL3rInDxhasTsYSNXwURLQ4W14GInSBU/60ni6QA+FIsLrjGL+AGWImhZAvG0SHimyp6Gs5GL3QQkc3AHSEyYTqeWFm4ViuuErKWHN7wyl39h0bKbDgqjGOGqiePxP61jHlrNtCRW8C3nGjzeVzS+ABEVmGqBYKr5iG3ghjo7bSsf8leN23Lt9LEPbP24d/fIC9yFRtqMk89E8UsLbR8eAvpH3Kk6Iq+kgNpXcGM6FZ+WOItONsXF25657r5uxPncF57BHrXTIazm4Fl9ihuIQBQIewFsFQ2ss0IQnesfhz+rixhhtioz2iqKYtxpl2U3OWAhmfLeukmzXIZJ9LgssWIdjhnU05fRTL+lw++m0UpZfTM2c2uCkkxGDSEWIw3YC9sypRFCld7KeNA3175yI4RqlLNmSGVBVjNNjdwEnMwyVg/tjcJBOdGt9CiXYxcTdtP+YPAKCosByo7trfOz7jkScTBiZvuv9HZX2U7ZouanbHJT6ryVEIoEmqn3CmPZ784CEJM6gC02bmLcOB5WyTSeWwnDnyG4/dUFx2Ug4JU=

script:
- "./mvnw clean package"
- docker build -t $IMAGE_NAME .
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push $IMAGE_NAME:latest

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

deploy:
  provider: heroku
  api_key: "$HEROKU_API_KEY"
  app: numberguess-game
  on:
    repo: USF53/NumberGuessGame
