language: java
jdk: openjdk16
script:
- java --version
- "./mvnw clean install"
- "./mvnw test"
deploy:
  provider: heroku
  api_key:
    secure: rTz5qcQPgOYxZDkfwQlsieyL+gB57SgNxgJOhdSS+Rj9wX5Yw7ko/E3Xx+RZuwbmzpL0NRJITukXnVCwICUzveNRmzQf/aBe9QKD7ALlGAVy/sc4R0kLPy5WBX1ae5uf0iXlADwNKpXUrn0GWTwkpM96eClixz+8sQguc4YM9Shnh4aiJNQMFdbycMgPSMNOs1ksw3pz2eOpFMWjEzDVaOP37ATH9eCJ6iqFkSYGVbzdE4IMxUz22WcuIU7ufbxDqpesYOmOvHwMH6IetLLWV+ByIdPYgR+K0+z+DyK3oTs84gIrsf42VV0c71ecDg/3ErHURMJ0dP8DJ8g2JCQXVpDo4ap13jnPHj7AuLiaUVYtPPfoox4Umd/NwnnfXI537ycaq1m7Fo6wm2O3bv04xVA0CSX6h0y1yaq71igYyc4yxmkatr0cIWI/CyF9tE6i8ZpmeQ5JUxBPLhAMd3n1Rv9qIbCaOfcm1JcG6sWz0GhtvTPXzJFd+xYcFSGXMA8yTbki/jne350p8LRza2nSut7IvAIP7uCKc/w6yARm8sF8BRNwndtGx+bEGklRlKLVv/2t94eadWomZL07UhVdHJcDh0t3OCKJjE1TFhmI8eI3govXo7hwRSL9+d9OlQlps2LfBmWRGnNdnw7muahM1AUU/DEpYvSnsmd9P+6PjWM=
  app: numberguess-game
  on:
    repo: USF/NumberGuessGame